### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [ibigbug/support-gbk#7]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`1.1.0`) of this package:

1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
1. Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows: ```json "activationCommands": { "atom-workspace": ["foo:bar", "foo:baz"], "atom-text-editor": ["foo:quux"] } ```
1. Use Workspace::onDidAddTextEditor instead
1. Use TextBuffer::onDidConflict instead
1. Use TextBuffer::onDidDestroy instead
1. Use TextBuffer::onDidReload instead.
1. Use TextBuffer::onDidSave instead. A TextBuffer instance is no longer provided as a callback argument.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see what deprecations are being reported on this package.

See https://github.com/atom/atom/issues/6867 for more info.

**Comment by iamstarkov** [comment]
![screen shot 2015-06-05 at 12 46 15](https://cloud.githubusercontent.com/assets/559321/8004553/de4dd036-0b80-11e5-8067-9b4b425917e0.png)

**Comment by iamstarkov** [comment]
@ibigbug can you do something with this?

**Comment by ibigbug** [comment]
@iamstarkov Hi. I'm sorry to reply so late.

I removed the deprecated API calls just now which may cause some issues 'casue the API changed.

In fact, Atom can now work with multiple encodings **by default**, so people may not need this plugin anymore :)

**Comment by ibigbug** [comment]
@benogle Done in v2.1.1

**Comment by iamstarkov** [comment]
@ibigbug thanks for response and explanation
